services:
  # Base de Datos PostgreSQL
  database:
    image: postgres:16-alpine
    container_name: rrhh_database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-rrhh}
      POSTGRES_USER: ${DB_USER:-rrhh_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rrhh_secure_password_2026}
    volumes:
      # Volumen persistente
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - rrhh-network
    #Comprobar si esta correctamente levantado
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-rrhh_user} -d ${DB_NAME:-rrhh}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Api Rest NodeJs Express
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: rrhh_api
    # Reinicio automatico en caso de fallo inesperado
    restart: on-failure
    environment:
      API_PORT: ${API_PORT:-3000}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-rrhh}
      DB_USER: ${DB_USER:-rrhh_user}
      DB_PASSWORD: ${DB_PASSWORD:-rrhh_secure_password_2026}
    ports:
      - "${API_PORT:-3000}:3000"
    networks:
      - rrhh-network
    depends_on:
      database:
        condition: service_healthy

  # Web Frontend Nginx HTML CSS JS
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: rrhh_web
    # Reinicio automatico en caso de fallo inesperado
    restart: on-failure
    ports:
      - "${WEB_PORT:-8080}:80"
    networks:
      - rrhh-network
    depends_on:
      - api

# Red Privada
networks:
  rrhh-network:
    driver: bridge


# Volumen persistente
volumes:
  postgres_data:
    driver: local
